### ISSUE TITLE
Error with libWrapper

### ISSUE THREAD

**Issue by Wombees** [bitkiller0/spellTemplateManager#20]
Foundry v0.8.8
spellTemplateManager v2.0.0
libWrapper v1.7.3

Console shows this error, tested with no modules running (other than spellTemplateManager and its dependencies):
```
VM372:8 I: Error detected in module 'spellTemplateManager'.
Module 'spellTemplateManager' is not allowed to call libWrapper with package_id='spellTemplateManager2'.
    at J (http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:27804)
    at Function.🎁register [as register] (http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:28889)
    at http://localhost:30000/modules/spellTemplateManager/scripts/Hooks.js:20:24
    at Function._call (eval at <anonymous> (http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:33400), <anonymous>:4:14)
    at Function.callAll (http://localhost:30000/scripts/foundry.js:153:12)
    at Game.initialize (http://localhost:30000/scripts/foundry.js:4190:11)
    at L.🎁call_wrapped [as call_wrapped] (http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:15461)
    at Game.🎁libWrapperInit (http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:34746)
    at Game.🎁Game.prototype.initialize#0 (http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:12184)
    at window.addEventListener.once (http://localhost:30000/scripts/foundry.js:53180:26)
```

**Comment by bitkiller0** [comment]
Resolved in 2.0.1
